### ISSUE TITLE
Is it ok to use this material to structure a course with due credits?

### ISSUE THREAD

**Issue by abailly** [aphyr/distsys-class#13]
I am giving a course on "distributed programming" in a local college and just find your approach almost perfect, so I wonder how I can use this material.

**Comment by thedrow** [comment]
According to the README, it's copyrighted and no license is provided.
So no, unless you get written permission to do so.

**Comment by aphyr** [comment]
Yeah, I'd prefer no in this case, although you're welcome to link to the outline as a see-also resource. This is something I put a ton of work into, and it's also a primary source of income for me.

**Comment by abailly** [comment]
No problem :)

**Comment by aphyr** [comment]
Thanks Arnaud :)
