### ISSUE TITLE
What's the deal with GPS?

### ISSUE THREAD

**Issue by ghost** [aphyr/distsys-class#4]
Sorry if this is unwarranted, but I stumbled onto this repo and started reading.

Given that I can buy a GPS and realtime clock for relatively cheap, and certainly finagle that into some fast bus on general purpose hardware, why all the doom and gloom about how GPS is "hundreds of dollars" and "Google is the only one"?

The text is brief class notes, I understand. I was just thoroughly baffled by that. There's got to be more to the story.

**Comment by aphyr** [comment]
It's not really doom and gloom. It's just not as easy as you might like. Try it and see.

**Comment by km-nglb** [comment]
@ghost @aphyr

又一个刷星的。账号创建时间精确到分钟级都接近。没什么好说的了。
