### ISSUE TITLE
Add register operation semantics for sequential consistency and linearizability

### ISSUE THREAD

**Issue by tmasternak** [aphyr/distsys-class#8]
[Sequential](https://github.com/aphyr/distsys-class/blob/master/README.markdown#sequential-consistency) consistency and [linearizability](https://github.com/aphyr/distsys-class/blob/master/README.markdown#linearizability) are both characterized by 

> All operations appear to execute atomically

Should that be rephrased to

> All operations appear to execute atomically with Read-Last-Write semantics?

**Comment by aphyr** [comment]
No; neither system necessarily has reads or writes, and for read-write registers, sequential doesn't necessarily imply read-last-write; only read-your-write. That's implied by "Operations from a given process always occur in order".
